name: Image-Build & Push

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write # This is required for requesting the JWT
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2.0.0
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/${{ secrets.ECR_ROLE }}
        aws-region: sa-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1.6.0

    - name: Connected to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        echo "Registry: $ECR_REGISTRY"
        ls -al
        # docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.14.2/pack-v0.14.2-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack

        # Build app with pack CLI
        pack build spring-boot-buildpack --path . --builder paketobuildpacks/builder:base

        docker tag spring-boot-buildpack performance-test:latest
        docker push  $ECR_REGISTRY/performance-test:latest
